### ISSUE TITLE
[Nitpick] Use title case for the context menu entries

### ISSUE THREAD

**Issue by FatOrangutan** [dessant/search-by-image#1]
This add-on is great! Thanks for writing it.

A very minor issue: please use the title case for the context menu entries added by the add-on, keeping in line with all the other context menu entries and the [Firefox design guidelines](http://design.firefox.com/photon/copy/copy-rules.html#capitalisation-on-firefox-for-desktop).

**Comment by dessant** [comment]
Thanks @FatOrangutan, and lovely username! 💯 

I'm glad you pointed out the guidelines, I was not aware of them.

**Comment by dessant** [comment]
I plan to release a version for Chrome and the rest, and they do not seem to use title case in context menus.

I will keep the current locale file as the base version and a Firefox specific locale will be applied to it during build time to override certain messages. This way we only have to maintain a subset of messages in the Firefox locale instead of duplicating the file in its entirety.
