### ISSUE TITLE
Search from clipboard

### ISSUE THREAD

**Issue by aranapatona** [dessant/search-by-image#114]
**Is your feature request related to a problem? Please describe.**
Allow the extension to use images that do not come from the browser.

**Describe the solution you'd like**
Let it search images that are currently on your clipboard, without having to take them from the browser first (it can come from an email or some other app).

I think you already do this but as part of another function, (Select & upload?) It would be a matter of just calling the upload part if there is an image on clipboard.

**Comment by neoOpus** [comment]
This is a must

**Comment by neoOpus** [comment]
> The discoverability is a bit poor, but you can already do this by selecting the "Browse" option in the extension popup, choosing your desired search engine, and then pasting your image to the newly opened tab.

Yes this isn't intuitive at all, and if I didn't read your comment I will not find out.

**Comment by dessant** [comment]
Upcoming changes:
![clipboard_1](https://user-images.githubusercontent.com/7513068/159496076-b6a8e127-6e57-463c-91b6-31d8d06bca1b.png)

**Comment by dessant** [comment]
Images from the clipboard are automatically detected in the browse search mode. If no image is selected in the popup, clicking a search engine will bring up the browse page like before.

The browse page is not removed because this new feature won't be available everywhere due to browser limitations. Firefox for example cannot extract files from the clipboard in all cases, and it closes the popup if we open the file selection dialog.

**Comment by stdanc** [comment]
I don't like the idea that for this to work you must have access to my clipboard (I noticed today you request permission to "read data you copy and paste"). I can have sensitive information on my clipboard.

**Comment by dessant** [comment]
Version 4.7.0 supports searching with images from the clipboard, and it has already been published for Chrome and Firefox. A new permission is requested for accessing the clipboard when the extension is updated. Switch to the Browse search mode after installation to begin searching from the clipboard.

The best browsers to try these new features are Chromium based browsers on Windows and macOS. There are some issues due to platform limitations:

Firefox:
* Browsing from the popup is not possible because the popup is dismissed when the file selection dialog is opened on desktop browsers, and the change event is not fired on Android
* Pasting an image copied from the file explorer does not work on Windows and Linux, the clipboard will contain file paths instead of actual files
* Pasting an image on Android does not work

Safari:
* Images from the clipboard are not automatically detected, because each clipboard access must be manually confirmed using a native Paste button

Samsung Internet:
* The `clipboardRead` permission is not supported, and the Clipboard API does not seem to work for files
* Browsing from the popup is not possible because the popup is dismissed when the file selection dialog is opened

Drag and drop is now enabled for the browse page on iOS and iPadOS, it works as expected when dropping files from the Photos app to Safari in split view.

The browse page now also supports pasting images using keyboard shortcuts, or using the Paste button from the browser's main menu.

There are two new options for the extension:
* "Detect images from clipboard" in the Browser toolbar section when the Browse search mode is activated: it enables the automatic detection of images in the clipboard when the popup is opened in the Browse search mode
* "Confirm images from clipboard": it allows you to confirm images before searching begins when you press the Paste button on the browse page

When an image has been automatically detected or manually selected in the popup, clicking a search engine begins a search, otherwise the browse page is opened as expected.

Features that do not work at all have been hidden on some platforms, so you may see a new Browse and Paste button, or just one of them, or nothing new at all.

Please let me know if you discover any issues, I hope you'll enjoy these now tools!

**Comment by stdanc** [comment]
> Version 4.7.0 supports searching with images from the clipboard, and it has already been published for Chrome and Firefox. A new permission is requested for accessing the clipboard when the extension is updated. Switch to the Browse search mode after installation to begin searching from the clipboard.
> 
> The best browsers to try these new features are Chromium based browsers on Windows and macOS. There are some issues due to platform limitations:
> 
> Firefox:
> 
> * Browsing from the popup is not possible because the popup is dismissed when the file selection dialog is opened on desktop browsers, and the change event is not fired on Android
> * Pasting an image copied from the file explorer does not work on Windows and Linux, the clipboard will contain file paths instead of actual files
> * Pasting an image on Android does not work
> 
> Safari:
> 
> * Images from the clipboard are not automatically detected, because each clipboard access must be manually confirmed using a native Paste button
> 
> Samsung Internet:
> 
> * The `clipboardRead` permission is not supported, and the Clipboard API does not seem to work for files
> * Browsing from the popup is not possible because the popup is dismissed when the file selection dialog is opened
> 
> Drag and drop is now enabled for the browse page on iOS and iPadOS, it works as expected when dropping files from the Photos app to Safari in split view.
> 
> The browse page now also supports pasting images using keyboard shortcuts, or using the Paste button from the browser's main menu.
> 
> There are two new options for the extension:
> 
> * "Detect images from clipboard" in the Browser toolbar section when the Browse search mode is activated: it enables the automatic detection of images in the clipboard when the popup is opened in the Browse search mode
> * "Confirm images from clipboard": it allows you to confirm images before searching begins when you press the Paste button on the browse page
> 
> When an image has been automatically detected or manually selected in the popup, clicking a search engine begins a search, otherwise the browse page is opened as expected.
> 
> Features that do not work at all have been hidden on some platforms, so you may see a new Browse and Paste button, or just one of them, or nothing new at all.
> 
> Please let me know if you discover any issues, I hope you'll enjoy these now tools!

I would like to be able to disable this option and don't give the addon permission to my clipboard.

**Comment by dessant** [comment]
@stdanc, the extension can already access mostly everything you do in the browser. I of course understand the having as little access as possible is preferred, so in the future the extension will transition to optional permissions, but that is not yet practical because we have to support older browsers where optional permissions are either not supported, or broken.

During the rewrite for Manifest v3 around the end of this year we will probably begin to switch to optional permissions.

**Comment by ivnnv** [comment]
Coming late to this after opening an issue, I understand the context now but... I dont think a new permissions request that makes the browser warns you is the best approach, this really seems like a security thread. Is there an alternative?

**Comment by dessant** [comment]
@ivnnv, you can grab the extension from the releases page and remove the `clipboardRead` permission from the manifest, then turn off the "Detect images from clipboard" option to not see any errors, though this will break pasting in the extension. At the end of this year major changes will have to happen because of the deprecation of Manifest V2 in Chrome, and that's when we will transition to optional permissions.

https://github.com/dessant/search-by-image/releases

**Comment by ivnnv** [comment]
Hmm no thanks I think ill just install the previous release, thats too much work for a feature that almost nobody asked for, you are going to (already are) be 1-star reviewed on the store for this because people is pretty aware of privacy nowadays, just saying.

**Comment by peddy22** [comment]
as if some malware developer is sitting on Github actively answering community questions without 10 minutes, i'm not worried

**Comment by dessant** [comment]
@ivnnv, I've offered you a temporary workaround, though reading your last comment and your empty threats, I would honestly very much prefer if you'd uninstall the extension entirely and you'd stop benefiting from my work.

What you are expecting here is to do even more free work for you, and develop a personalized solution for YOUR use case and your browser only, and I think you need to take a step back and readjust your expectations.

As I've already said some of the browsers we need to support don't work properly with optional permissions, once you need to support all platforms the extension API becomes a minefield. We will break compatibility at the end of this year and stop supporting older browsers, so you can complain about that and [call me selfish](https://web.archive.org/web/20220330090712/https://addons.mozilla.org/en-US/firefox/addon/view-page-archive/reviews/1809048/) this Christmas, and that's when the switch to optional permissions is going to happen.

**Comment by HanabishiRecca** [comment]
I came here expecting someone will be upset for sure.
But relax, the extension already had `Access your data for all websites` and was able to track you anyway. Complaining about the clipboard is kinda ridiculous now.
Btw any website can mess with your clipboard, thanks to [Clipboard API](https://developer.mozilla.org/docs/Web/API/Clipboard_API). There are some restrictions, but still.

**Comment by Oha-you** [comment]
Dear author, please don't be discouraged by those pesky 1-starrers. You're doing a great work! 
If people can't do their own research and are so afraid of open-source extensions, maybe it's alright for them to uninstall it.
Also I'm sure that if Chrome allowed you to add an explanation about why a new permission was requested, it would eliminate all the confusion. It's bad UX how it happens right now: in an alarming way as if the extension developer means harm.

After Chrome replaced their "Search by Image" functionality with this stupid Google Lens, I found your extension and I couldn't be happier. I can do so much more now thanks to all the features you've already added. No other extension comes even close to yours, so I hope you'll find the time and interest to continue to support it. Thank you 🙌

**Comment by stdanc** [comment]
First of all I also appreciate the work on this app a lot. I love it and use it very often and I appreciate a lot developers like you, [dessant](https://github.com/dessant) as I understand that you do not earn anything from developing addons like this one.

Second, I think our concerns might be not understood and probably also not founded. This might sound silly. Could this new permission grand access to our clipboard all the time as long as the addon is active?  Considering I want to send some important bank information or my ID to someone, or a crypto wallet seed on messenger/ email etc.  would this permission mean that this information could be collected anytime (I know it states that it doesn't) by the app?

**Comment by HanabishiRecca** [comment]
> Could this new permission grand access to our clipboard all the time as long as the addon is active?

Yes. This permission grants access to [Clipboard.readText()](https://developer.mozilla.org/docs/Web/API/Clipboard/readText) function. Which returns the current clipboard content.

![image](https://user-images.githubusercontent.com/13597663/160833653-21fac9f9-59a6-478b-8cf8-e74c2d6f6ab9.png)

**Comment by dessant** [comment]
@Oha-you, thanks for the encouragement, I'm happy you like the extension! :yum: 

@stdanc, it depends. When your browser is open and the extension is enabled, the extension could access the data you copy and paste outside of the browser. If you're worried about a malicious update, you could close the browser or disable the extension when handling sensitive data on your device.

Though sensitive clipboard data usually lands in the browser at some point anyway, be it pasted passwords while signing in, or pasted credit card details, at which point the extension can access the data, because it can access everything on the web page, regardless of clipboard permissions. A malicious update would achieve it's goal much faster, and it would not need to periodically check the clipboard in the hope that something sensitive might be copied, the data would be typically introduced in the active tab by the user.

I recommend this extension made by a Mozilla engineer for checking the source code of extension updates, though it needs a bit of programming knowledge to spot issues:

https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin?hl=en
https://addons.mozilla.org/en-US/firefox/addon/crxviewer/

Obfuscated code is not allowed on extension stores, so if you see anything that is not just minimized, but obfuscated, report the extension immediately.

**Comment by dessant** [comment]
@stdanc, regarding earnings, this extension was initially developed in 2017 for personal use. I've started accepting donations after my projects have gained popularity, and by now the development of all my projects is entirely funded by users through donations and purchases on the App Store and Galaxy Store.

**Comment by Natrox** [comment]
> Hmm no thanks I think ill just install the previous release, thats too much work for a feature that almost nobody asked for, you are going to (already are) be 1-star reviewed on the store for this because people is pretty aware of privacy nowadays, just saying.

You're free to fork! That's the beauty of open-source.

**Comment by fhtdtdj** [comment]
Also voicing my concern about this permission update issue.

**Comment by dessant** [comment]
The feature won't be removed just because some of you are concerned about a permission request, no matter how many 1 star reviews you submit on extension stores in an attempt to punish the project. Your concerns are reasonable, but some of your reactions are ignorant and out of line. You've already got an explanation and a planned roadmap that will address your concerns, and repeating the same responses will not lead anywhere.

Adjust your behavior if you perceive this software to be a threat, and don't waste my time by opening new issues, sending emails, or sending private messages on Twitter.

**Comment by dessant** [comment]
> you may want to post a small explanation or recent changelog at the bottom of the extension description on the extension store

You're absolutely right, and ideally we should be able to provide a reason for requesting a permission that is displayed by the browser along with the request. Giving no explanation for permission requests that are coupled with automatic updates while browsing can rightfully scare users.

Mozilla is a bit better in this regard, there is a dedicated section for extension release notes in the browser and the extension store. They also keep the previous extension version enabled when a new permission is requested, while Chrome disables the extension and pulls the rug out from under the user in the middle of the browsing session.

This difference in strategy can be seen in how users have reacted. The extension has twice as many Firefox users, but only received 2 negative ratings (plus one that was removed for profanities), while on the Chrome Web Store there have been 22 negative reviews since the update.

**Comment by grahamperrin** [comment]
<https://github.com/dessant/search-by-image/issues/114#event-6319645396=>

Thanks for adding this feature, and for providing release notes.

**Comment by dessant** [comment]
Version 4.7.0 was just submitted to be reviewed for Edge and Opera, please let me know @neoOpus if you find any issues on Edge.

**Comment by Pandaa-P** [comment]
I don't see why a lot of people are mad? you know you can rollback to version 4.6.0 if you didn't like v4.7.0 right?   
I was hoping that pasting an image copied from the file explorer will work, apparently the extension doesn't recognize the copied data as an image when copied from windows explorer.   

[Armin](https://github.com/dessant) thank you so much for your amazing work, all these years you spent your time and effort to develop `search-by-image` and other extensions and give support. 

Thank you so much for making my life easy.

**Comment by dessant** [comment]
Hi @Pandaa-P, I'm glad you found the extension useful! I'm guessing you're referring to Firefox, there are browser bugs that prevent the feature from working properly. I could only paste an image from the Files app on macOS, but on other platforms Firefox did not receive the actual file.

Though you could still use the paste feature for example after capturing a portion of the screen with the Snipping Tool on Windows and copying it to the clipboard, Firefox will detect the copied image. This should also work from other software that allows copying the image data directly.

As for why people are *mad*? I have my opinion about them, but they've embarassed themselves enough already. I can understand when someone is startled and becomes concerned given Chrome's horrible extension UX, but that does not excuse their unwillingness to analyze the situation and click on the Support tab on the Chrome Web Store, which is right next to Reviews. They don't understand the value of the tools they were given, and they don't care about the harm they cause to other people.

Sadly they are also harming the project, the average rating of the extension has fallen from 4.7 to 4.3 so far on the Chrome Web Store, which could affect search ranking. I have marked a couple of rude reviews as abuse, but they haven't been removed.

**Comment by shultays** [comment]
You may want to explain the reasons for the new permission requests in release notes or in the extension page. In an age where extensions are regularly hijacked or sold imo it is needed

I am not mad for additional permissions but it is slightly annoying that I need to search for this thread to figure out what is going on

**Comment by sadsayeed** [comment]
'Search by Image' extension was and still is a fantastic extension, so, truly thanks to the Developer for all their hard-work; still 5-star from me for that. However, now it's asking for system-wide 'Mandatory Clipboard Permission' [i.e. not Optional].

I know the explanation says it already has access to ALL data on ALL websites, so not a new concern, plus older version browser-users are an issue... but forgot to consider that it does NOT have access to Firefox "Private Window" for banking transactions and other sensitive browsing. 

Moreover, 'Mandatory Clipboard Permission' fetches data from outside the Firefox, access system-wide and not limited to browser-only or image-only content... i.e. all text and everything, which makes it hugely vulnerable for passphrases or other sensitive data to be used inside the "Private Window" of browsers anymore...

Prior Disabling and later Re-enabling extension before and after every banking transaction is not also a good or practical option, neither is keeping to using the older release and never updating... 
Some vulnerable permissions such as all system-wide 'Clipboard' access need to be enforced by Mozilla to be kept as 'Optional' and initially 'Disabled'... especially when something Firefox / Mozilla / Chrome itself 'Recommends'; it's absolutely important to consider to avoid uncertain possibility of security and privacy breaches via firefox / browser or its recommended extensions.

Again, please Developer, please don't feel that I'm unreasonably complaining, or undermining your fantastic efforts that you give for the world, really really appreciate your works, but please please consider various scenarios and possible dangers in it. Thanks a ton, again.

**Comment by dessant** [comment]
@sadsayeed, I'm glad you have reached out about your concerns, but clipboard access itself is not a security vulnerability. This is software that needs a certain level of access to perform its function. Please take a look at Bitwarden, it requests mandatory clipboard access upon installation, for a feature that is not essential.

https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=en

Would you consider Bitwarden to be vulnerable software, with lax security practices? If yes, security researchers may have a different opinion.

https://bitwarden.com/help/is-bitwarden-audited/

I understand that some of you don't care about the new feature, and for you the new permission brings no value, but only a perceived additional risk. Optional permissions are an answer to this issue, and that is why there is a plan to migrate to a new installation process that will let you either give access to everything that is needed for the software to perform its function, or opt to authorize access only when needed.

Implementing such a model has a considerable development cost, especially when you need to support every perceivable platform, and will inevitably lead to the deprecation of support for some older browsers.

Software never exists in an ideal and perfect state, there is always a new, better solution to adopt. The reality is that we have to make technical compromises all the time in order to deliver features with a reasonable development cost, and without leaving users with legacy browsers behind while we chase those ideals.

I think the most important issue here is trust. You have to trust the people who develop your software, unless you are able to verify the software you install before every update. An open source project makes verification easier, but verification still has a prohibitive cost, so you ultimately need to trust the developers of the project.

Unless you read the code yourself, there is *nothing* that can stop a developer from exploiting you on the first install or during an update. Reviews by extension stores will help, but are by no means adequate protection against a malicious update. Optional permissions also won't protect you against a motivated adversary, they will find a way to achieve their goal, without alerting you.

Your best protection against malicious updates is to use software that is open source, and has a sustainable development model. Who pays for the development of the software you use, and what are the motivations of the developer? That is always something you should research before installing any software, especially when it comes to popular projects.

**Comment by dessant** [comment]
Clipboard access will become optional in the next release (version 6.0.0), a permission request will be shown when the Paste button is clicked: https://github.com/dessant/search-by-image/commit/f805a490e9a08ef6371f39bc7f7d38b47fe281e9
