### ISSUE TITLE
search_by_image-X.X.X-samsung.zip

### ISSUE THREAD

**Issue by AdamKane41** [dessant/search-by-image#124]
For Samsung Internet Add-Ons on Android Devices, **Search-By-Image** is only available to install via the Samsung App Store. And is behind a 7$ (Maybe a bit more) paywall... 

Could it be possible to make the Android Install File (.apk) available on a alternative Repo or Storage Location to enable "side-loading" installation in order to test and try its features before committing to a Purchase? 

ALOT of users have good faith and only use non-paid apps versions to evaluate if the Apps is working adequately on their Setups, and to determine if it suits their Needs / Expectation before installing it from the Official Dev for a Premium$.

I just finished reading all the codes in the Github Repo for the App and it looks like a Samsung Version is Compiled and Zipped ( **search_by_image-X.X.X-samsung.zip** ) alongside the other editions when a new build is created, but seems to be hidden from the output... 

okydooky...thanks for your time, **Peace**

**Comment by dessant** [comment]
The extension can be purchased for Samsung Internet on the Galaxy Store, which partially funds the development of my open source projects. You can evaluate the extension in other browsers before purchase, though keep in mind that the capture search mode and searching with multiple engines at once is not yet available for Samsung Internet due to current browser limitations.

The zipped package is removed from the GitHub release because it is not useful to end-users (just like the Safari package), the Android app needs to be further packaged using proprietary tools provided by Samsung in order to be installable.

**Comment by AdamKane41** [comment]
Nice, thanks for the prompt and clear-readable-no-nonsence answer!

So apart for the " ..capture search mode and searching with multiple engines at once..." Features, will the extention behave relatively the same (mode of operations, Steps, Location of interactive elements, ect) on the other Chromium based browser variants? 

If so, ill go do what you suggested, and try out  Search-By-Image on my other Suported Chromium Based Android browsers! 
Peace 🐙
.
![demolitionman_seashells](https://user-images.githubusercontent.com/30092603/117197311-aa226a00-adb5-11eb-9cba-23d72026b40f.gif)

**Comment by dessant** [comment]
Yes, it should behave the same, with minor differences.
