### ISSUE TITLE
why do I have to add an image twice on Yandex??

### ISSUE THREAD

**Issue by DialexG91** [dessant/search-by-image#131]
instead of the image found on Yandex, the search box opens what clearly means that I have to research the image and reopen it into the box, why did you think this was a good idea?? put it back how it was

https://user-images.githubusercontent.com/66972445/121604551-5f2cef80-ca10-11eb-96d8-36c658a814c1.mp4

**Comment by dessant** [comment]
You're seeing a new version of Yandex that the extension does not yet know how to handle. I'm still being served the old version of Yandex, so we'll have to find a way to reproduce the issue.

Regarding the rest of your issue, when the extension was not updated for a while, but it suddenly breaks, it's usually because of a browser update, or a site that has changed. Regardless, you're not in a position to behave the way you did, but fill out the issue template properly and ask nicely for help.

**Comment by DialexG91** [comment]
then you can now delete Yandex from the extension
