### ISSUE TITLE
What does the "Bypass image host blocking" option mean?

### ISSUE THREAD

**Issue by artquest** [dessant/search-by-image#137]
Hi,
thank you for the extension!
Can you please explain what does the **"Bypass image host blocking"** option mean?

**Comment by dessant** [comment]
Search engines from Mainland China block certain image hosts when you search with a URL. When the option is enabled, the extension will always upload the image file to these engines instead of searching with the URL. It essentially acts as if you'd have used the `Select & Upload` search mode, even if you have the `Select` search mode selected at the moment.

These are the censored engines: https://github.com/dessant/search-by-image/blob/7f6f9686b9e6478b56a9d779f150caa663f46cf9/src/utils/data.js#L330-L337
