### ISSUE TITLE
Plug-in not working with 3.9.0 version

### ISSUE THREAD

**Issue by DO97** [dessant/search-by-image#141]
Since the latest update, I cannot access the settings web page. The plug-in was also initially disabled and even if I turn it on, the "Search by image" option is not showed.

Samsung Internet Browser 15.0.2.47

**Comment by dessant** [comment]
Hi, thanks for the bug report. I've just tested an update from 3.7.0 to 3.9.0 through the Galaxy Store, and the extension was updated without any issues in the browser.

Sometimes Samsung Internet can mess up extension states, could you try disabling the extension and enabling it again after a browser restart?

**Comment by DO97** [comment]
Nothing. I also restared the phone, but nothing changed.

**Comment by dessant** [comment]
Please try uninstalling the extension app using the Galaxy Store or your phone's app settings, then restart the browser and see if the extension has disappeared from the browser's add-on list. If it did, install it again from the store. This should clear the extension's storage in Samsung Internet, and you can enable it again from the Add-ons page.

**Comment by DO97** [comment]
It worked yesterday. Today is not working again.

**Comment by dessant** [comment]
I think this is a bug in Samsung Internet with the way extensions are loaded, you may want to report this issue directly to the Samsung Internet extensions development team (sixsupport@samsung.com), or this forum: https://forum.developer.samsung.com/c/samsung-internet

As an absolute last resort to work around the issue, you could completely wipe the app data of Samsung Internet, but make sure to sync your browsing history and bookmarks using your Samsung account beforehand, otherwise your data will be lost.

If you still can't use the extension after resetting the browser, feel free to forward the purchase receipt email you have received from Samsung to galaxy-store-support@armin.dev, and I'll request a refund for your purchase.
