### ISSUE TITLE
Context menu problems

### ISSUE THREAD

**Issue by nimbus2332** [dessant/search-by-image#151]
**System**

* OS name: Windows 10
* OS version: 21H2
* Browser name: Vivaldi
* Browser version: 3.7.2218.58 (Stable channel) (64 bit)
* Extension version: [4.3.1]

**Bug description**

Applications are constantly hibernating, constantly disappearing from the context menu.

Every time I have to open and switch the search method: URL or images, only after that I can select a picture through the context menu of the browser.

Fix the problem, the latest update is extremely annoying.

**Logs**

```
no errors

```

**Comment by dessant** [comment]
What does "applications" mean? Are you referring to this extension only, or do you use other extensions too that disappear from the context menu?

Since when have you been using the extension, and when did you first notice this issue?

**Comment by mikamidd** [comment]
I noticed this issue on Microsoft Edge too but not just with this extensions, uBlock Origin and Saucenao extensions also disappear from context menu sometimes.
The way I fix it is by toggling "enable context menu" switch in Search By Image settings. Not only this brings up SBI back to the context menu but also other extensions missing from menu such as uBlock.
Absolutely no idea what's causing it though, if it happens on Vivaldi too then it could be some Chromium issue?

**Comment by dessant** [comment]
@mikamidd, thanks for sharing these details. It sounds like this is a Chromium bug indeed, extensions should not be able to remove context menu items belonging to other extensions. When you toggle the context menu option in Search by Image, I'm guessing it forces to recreate the entire context menu, and that brings back the menu items removed by the browser bug.

Please let me know if you find a way to trigger the issue.

**Comment by mikamidd** [comment]
@dessant after fiddling with extensions some more it looks like Incognito window is what breaks context menus.
It seems that context menu breaks only for extensions that are allowed to run in Incognito mode, once you remove that permission, context menu for that particular extension works fine.

What happens is, if extension is allowed to run Incognito and you open Incognito window, context menu in the "main" window breaks. But sometimes Incognito window has working context menu, as in SBI is missing from main window but visible in Incognito context menu. Removing permissions from extension to run in Incognito mode fixes context menu issues, but it's not ideal since I'd like to have SDI in Incognito mode too.

Since this was happening to uBlock Origin too I went searching the UBO issue tracker and found a similar report: https://github.com/uBlockOrigin/uBlock-issues/issues/1646#issuecomment-950111411

Possibly some other extensions with context menus are affected too, but doesn't look like all extensions are affected since I run Windscribe in Incognito mode and its "debug log" context menu seems to never encounter this issue.

> When you toggle the context menu option in Search by Image, I'm guessing it forces to recreate the entire context menu, and that brings back the menu items removed by the browser bug.

Could be, since toggling the context menu option fixes all the broken context menu items, not just SBI one.

**Comment by neoOpus** [comment]
I think this issue is finally fixed!!!
