### ISSUE TITLE
Yandex search dosent work

### ISSUE THREAD

**Issue by redlack2** [dessant/search-by-image#155]
**System**

* OS name: [Windows]
* OS version: [11]
* Browser name: [Firefox]
* Browser version: [ 95.0.2 (64-bit)]
* Extension version: [4.4.0]

**Bug description**

**Comment by dessant** [comment]
Version 4.4.2 will fix the issue, it is currently under review on AMO.

**Comment by alexolog** [comment]
One of the reasons I suggesting using the API the last time Yandex search broke was that it is usually more stable than the web page layout

**Comment by dessant** [comment]
@alexolog, we use the API when the user interface for reverse image search is not available. I've decided to hook into the website UI whenever possible, because then we don't need to handle all the errors engines can throw in response to an uploaded image. We don't have to replicate and maintain already present website features this way, and we don't have to always reverse engineer every service. Even when we use the private API directly, we sometimes have to access the DOM for tokens, and upcoming features, such as search engine customization will also require interacting with the DOM.

It is much more maintainable to hook into the user interface of search engines, than to replicate the essential parts of dozens of services, at least that is my experience.
