### ISSUE TITLE
Checkboxes to select search engines

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#161]
Hello,

I have an idea about having checkboxes showing when we hover over the search engines logo in the popup menu to be able to select the search engines that we want to search the selected or captured image into, this will make it easier to manage what tab needs to open in case by case instead of for example selecting all search engines and having dozens of tabs to close later or having to go to the settings and limiting the search engines every time...

I hope this makes sense, and it is not very hard to implant.

Cheers!

**Comment by dessant** [comment]
This is one way to solve the issue, but in practice you'll usually want to have a couple of groups of search engines that you use. Instead of manually toggling the engines before each search, you'll be able to define search engine groups and use those instead.

You can subscribe to this issue for updates: https://github.com/dessant/search-by-image/issues/68
