### ISSUE TITLE
Can't change order of context menu items anymore

### ISSUE THREAD

**Issue by ZenitH-AT** [dessant/search-by-image#180]
**System**

* OS name: Windows
* OS version: 10 21H2
* Browser name: Firefox
* Browser version: 98.0.2
* Extension version: 4.7.0

**Bug description**

The latest update or a recent one no longer lets you drag around search engines to re order them in the addon options page.

Is this intended?

After updating today, I checked the changelogs and noticed that Google Lens was added a few updates ago. I enabled it in options and wanted to drag it to a different position in the list but couldn't (so it would appear in a different position in the context menu and addon menu).

I'm not actually sure which version caused this but it was working last year. I also tested on Chromium, which I haven't used in a while. Same result after updating.

**Comment by dessant** [comment]
A small delay was added to support touch devices, otherwise the items would be rearranged when you swipe to scroll the page with a pen. You need to hold the click or touch for at least 120 milliseconds before you begin dragging the search engine. In the future there will be a dedicated drag element for each engine, and that will work without delay.

**Comment by dessant** [comment]
The library we currently use for dragging does not account for small natural hand movements during a touch, so your touch has to be completely still for 120 ms, otherwise it is discarded. :laughing:
