### ISSUE TITLE
Image dimension

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#185]
Hi,

I would like to make a suggestion to add the image dimension in the corner when it suggests to choose one like on this image

![msedge_1RRzjSpdt1](https://user-images.githubusercontent.com/1388336/162280528-88c4fad4-16f9-45d5-b0a3-5df524529c8a.png)

something the bottom-right corner or you know better!

**Comment by dessant** [comment]
Ah yes, that is definitely planned! It has been on my mind for some time, it will come in handy when we'll also parse `srcset` and offer the same image in multiple dimensions.

**Comment by dessant** [comment]
![screenshot](https://user-images.githubusercontent.com/7513068/166609258-49c0c841-f565-4a55-879b-a61589a72423.png)

**Comment by neoOpus** [comment]
Thanks 🙌

**Comment by dessant** [comment]
![1](https://user-images.githubusercontent.com/7513068/169385239-c39285af-f286-4b53-b770-f095702a446b.jpg)

**Comment by neoOpus** [comment]
Amazing improvement, Thanks for the update

**Comment by dessant** [comment]
@neoOpus, thanks for motivating me to add these features! I'm about to submit version 5.0.0 for review, you can also enable the "Detect alternative image sizes" option to display alternative sizes like in the screenshot above, though it comes with a bit of additional bandwidth cost because other sizes that were not cached by the browser need to be downloaded.

**Comment by neoOpus** [comment]
@dessant I am glad to hear that I am motivating you.

Regarding the bandwidth problem I understand what you mean and since it is JS you cannot use some solutions linke imagemagick to ping the images and get their properties, though here something I've found (https://github.com/sdsykes/fastimage) Not sure if you will find it helpful but it is implanted in several languages...

Also I am using this user script to image dimensions in google image search ()https://greasyfork.org/scripts/401432-google-image-search-show-image-dimensions/code/Google%20Image%20Search%20-%20Show%20Image%20Dimensions.user.js) maybe it is possible get the dimensions from a url search or some "obscure" API...

Thank you for your time

**Comment by dessant** [comment]
FastImage could be useful for specific cloud providers, but our main reason for downloading the images is to preview them in the confirmation dialog, and of course we also get reliable image metadata for free that does not depend on the hosting provider's server configuration or an API. On my part the feature worked fine, it's just something to keep in mind if you have a metered or spotty connection.

**Comment by neoOpus** [comment]
Ah, yeah I am aware that FastImage and almost all other solution rely on some sort of executable to parse the image's metadata or header and get the information from it without the need to download it all… but I was looking if there is a WebAssembly implantation or something, I am sure your solution works pretty fine, and I will not have an issue with it myself as my internet is pretty fast and unlimited, and I am suggesting this feature just to improve on what it already great… I would like to learn more about how to solve problems like this one even if myself I am not a coder… I suggested this so to sort of mitigate the problem for most other users (also have a more elegant solution)… or maybe a hack that uses just free API by doing the proper request for the image URL and getting from it the required information (I am still looking at this option), anyway I hope I didn't distract you with my propositions!

**Comment by dessant** [comment]
No worries :yum:, I've actually bookmarked FastImage because it could be useful for my work in the future. There are some avenues for optimization, but ultimately we have to download the image itself, because the user must see the actual image in order to decide if they want to upload it to a search engine, and there is no universal way to request only a small thumbnail of the image from the server.

An attempt at optimizing would be to just download a single image and display it multiple times, along with the correct metadata for each image that was fetched from the server with something like FastImage. The problem is that the developer could list images with different visual content in the same `srcset`, not just the same image that has been resized. For example, they may use stock photos of birds as an illustration, but show different birds on mobile and desktop.

So this optimization method could only be applied in a limited number of cases, when we can identify a couple of known image hosting services, such as  [Cloudinary](https://cloudinary.com/documentation/image_transformations), where the same file id means we are served the same visual content, depending on the URL parameters we send.

**Comment by neoOpus** [comment]
Right now it works perfectly!
