### ISSUE TITLE
Show context menu items on extension pages

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#195]
Hi Armin

I hope you are doing great,

I just found out that the extension doesn't work on this sort of address extension://cnojnbdhbhnkbcieeekonklommdnndci/src/view/index.html?id=

Some other extension do.

**Comment by dessant** [comment]
Hi @neoOpus :yum:, the extension is not shown in the context menu because we cannot inject a content script in the page of another extension. There is some limited use for adding it to access images that are also recognized by the browser as images when you open the context menu.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData

The extension already uses the `srcUrl` from the context menu event if injecting scripts in the page is not allowed, so we would only need to expose the extension in the context menu.

Please share an extension you would use this feature with for testing.

**Comment by neoOpus** [comment]
You are right, excuse my ignorance, I am aware that there are many security limitations, but I don't have a grasp of them as a dev does

**Comment by dessant** [comment]
This change will also let us use the context menu on our own extension pages, such as the confirmation popup that is shown when multiple images are detected.

**Comment by neoOpus** [comment]
Amazing as usual 👍🏼
