### ISSUE TITLE
Toggle in page toolbar

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#205]
Hi,

An idea just came to my mind and I would like to share it with you,

First it would be to have the possibility to create named groups of search engines that work with the right click menu and the pop-up window… something like some extension manager does to quickly enable and disable some extensions… but it would mainly search on the same group that *in a background tab (I am aware that you can do search all but having many services enabled all the time require disabling some of them to make this feature really usable.

Second, it would be great to have the possibility to open a toolbar that can be added as several features (https://greasyfork.org/en/scripts/445274-searchjumper) … like this one in terms of appearance or maybe like this https://extensions.redeviation.com/#bs
or maybe even better something like this one (https://chrome.google.com/webstore/detail/gitako-github-file-tree/giljefjcheohhamkjphiebfjnlphnokk)

That allow to drag and drop the image(s) to the required search engine or group that will open in background, so we keep doing what we do while the search engines are looking for the image…

**Comment by dessant** [comment]
Absolutely, I'd like to finally implement search engine groups before the Manifest V3 migration: https://github.com/dessant/search-by-image/issues/68

Regarding the toolbar, it would not be secure, so we'll explore other convenience features for now, before injecting a UI that accepts user input in web pages. See this comment about possible new features, one would be to implement a sidebar, but I think the API is only supported by Firefox and Opera: https://github.com/dessant/search-by-image/issues/188#issuecomment-1107790092

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction

It would also be nice to just drag and drop an image on extension icon in the browser toolbar, and that would open the popup and process the image, but this does not seem to work in any browser.

One alternative to this would be to have an option for the Browse page that keeps it open after the image has been selected. This would enable us to create a pinned tab with the Browse page, which allows you to drag an image from any page on the pinned tab icon, which then causes the pinned tab to become active, and then you'd drop the image in the pinned tab. I've just tested this in Chrome and the image was successfully processed, we just have to keep the pinned tab open with a new option, and switch back to the previously active tab after an image is dropped. There could even be an option to automatically pin a tab with the Browse page when the browser is started, so it's always there when you need it.

There are a lot of avenues that we could take, but I'm not sure what will stick after the coming changes caused by Manifest V3. I'll probably modify the Browse page first so it stays open and accepts repeated searches, and we'll use that as a base for a sidebar and maybe a pinned tab.

**Comment by dessant** [comment]
@neoOpus, I've looked into the [Bookmark Sidebar](https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh) extension you shared, be careful how you use it. Any website can access your bookmark list once you open the sidebar, here's a snippet that grabs the name of the first bookmark.

```js
document.querySelector('iframe#redeviation-bs-sidebar').contentDocument.querySelector('#bookmarkBox .link .label').textContent
```

**Comment by neoOpus** [comment]
> 

Thanks for letting me know, I will contact the author of this extension to inform him

**Comment by dessant** [comment]
I've reached out a couple of days ago, and I see there is an attempted fix for the issue, but that code is still vulnerable. Closed shadow DOM is not enough to isolate content from the website and other extensions. A website can place a hook in the shadow DOM API before the extension calls `attachShadow()`, and will have access to the content of the iframe just as before. Other extensions will also have access to the closed shadow root, there is a dedicated API for it: [chrome.dom.openOrClosedShadowRoot](https://developer.chrome.com/docs/extensions/reference/dom/#method-openOrClosedShadowRoot).

https://github.com/Kiuryy/Bookmark_Sidebar/commit/bf0d806ad0eb3a2a53a1f5f4502302886714245a

The only safe and private way for an extension to embed content in a web page is to create an iframe and point the `src` attribute to a HTML document packaged with the extension, the URL can be created with [chrome.runtime.getURL](https://developer.chrome.com/docs/extensions/reference/runtime/#method-getURL).

If you contact him, please let him know that the extension will still be vulnerable with the most recent changes.

**Comment by dessant** [comment]
Though `attachShadow()` may not be a problem if it is called from the extension context rather than from a script injected in the page context, but other extensions which do not have the `bookmarks` permission will definitely have access to the bookmark list when Bookmark Sidebar is installed.

**Comment by neoOpus** [comment]
I contacted him today and he told me that you reached him already :)

**Comment by neoOpus** [comment]
I've sent him the link to this thread so I hope he will read your comment... as the GitHub of the extension doesn't have the issues tab.

Thank you again for taking care to analyse and report this.

**Comment by neoOpus** [comment]
This is what Philip told me btw before I send him again about your remarks 

"The issue potentially allows websites to read the bookmark titles (but not the urls). 
I already uploaded an update for this. The bookmarks are now encapsulated in a non-accessible shadow dom, preventing websites from reading them. Currently the update is rolling out and should be available in a few days or next week (Google review takes some time)."

-----------------------------------------------------------------------------------------------------------------------------------------
Myself thought and suggested to him that maybe if he adds some random numbers to the ID this can prevent but I am not a programmer but when I do some debugging of some extensions, I think I've seen this sort of practice, please ignore this comment if it doesn't make sense.
