### ISSUE TITLE
Capture doesn't work anymore in isolated image tab

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#214]
Hi,

I would like to report that the capture that use to work on tabs with these URLs (extension://cnojnbdhbhnkbcieeekonklommdnndci/src/view/index.html?id=) and (data:image/png;base64,) doesn't work anymore, it was an excellent option to be able to circumvent some limitation I am having in facebook who turn the page white when I click on capture... so I open the images in new tabs via your extension then do a capture search from there...

I hope this can be easily fixed.

Thank you.

**Comment by dessant** [comment]
Regarding the white screen, this may be the cause: https://github.com/dessant/search-by-image/issues/232#issuecomment-1595817124

Searching from the context menu should work in extension pages, the menu item should be present when you right-click on an `<img>` element. Though an extension page could use different ways to show an image, and we have no way to extract that content.

The context menu item is indeed not shown for data URI pages, I think it was done because of an inconsistency across browsers, but let's look into it, the issue is tracked at https://github.com/dessant/search-by-image/issues/254.
