### ISSUE TITLE
Google Image Search Doesn't Work

### ISSUE THREAD

**Issue by udu3324** [dessant/search-by-image#221]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable)
* Extension version: 5.3.0

**Bug description**

When right clicking on a image and searching using google, it pops up a new tab without searching for it.

**How to Produce Bug**

1, Have a image to test on
2, Right click the image
3, Click on Search by Image > Google
4, Observe the bug

https://user-images.githubusercontent.com/47045986/199403468-a1bf2f05-1e68-4349-90e9-fb20937da886.mp4

**Comment by tomsku** [comment]
Same here, new tab -> only empty Google Image Search page. Fedora 36 with Firefox

**Comment by dessant** [comment]
Is the issue also present with the "Select image" search mode, or just with "Select URL?

**Comment by udu3324** [comment]
I tried the Select Image mode and it worked

**Comment by github-nilsson** [comment]
Looking at the network trace the extension makes a "https://www.google.com/searchbyimage?image_url=" request with the URL to the image added to the end percent encoded. The google server then responds with a redirect to "https://www.google.com/imghp?sbi=1" with no intermediate steps.

**Comment by dessant** [comment]
I was able to reproduce this issue a couple of times, but only with Tor Browser. It looks like some visitors outside the US are now redirected to the homepage instead of their region-specific site when attempting to search with a URL using the legacy search service.

Here's an example for testing:
https://www.google.com/searchbyimage?image_url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F4%2F41%2FLethejalaurida.jpg

In some cases I was able to prevent the redirection by appending `&gws_rd=cr&gl=US`, but it did not always work.

It's not yet clear if this is a regression on Google's side or if they are slowly rolling out an intentional change in some regions, so it's best to switch away from this search method now.

When searching from the Chrome context menu while Google Lens is disabled, the browser appears to always upload the image, so it's possible that they are shutting down the legacy service responsible for searching with an image URL, now that it was completely replaced by Google Lens on google.com.

The easiest way to avoid uploading the image when the "Select URL" search mode is used would be to search with Google Lens and hide the results, while immediately redirecting to Google Images using the search results URL they provide.

**Comment by jaff80** [comment]
I have this bug and I selected the Google option.

**Comment by hejhopsa** [comment]
Please fix it :-((( 
it just opens https://www.google.com/imghp?sbi=1 and nothing happens (no popup window that the image is uploaded etc)

**Comment by dessant** [comment]
Switch to the "Select image" search mode until an update is realeased, you can change the search mode for the context menu and the toolbar popup from the extension's options.

**Comment by Player701** [comment]
Same here. Firefox 106.0.5 on Windows 10, extension version 5.3.0.

**Comment by dessant** [comment]
I did some further tests, searching with the image URL on Google Lens and then loading the provided Google Images link mostly works on desktop, but it returns a 404 status on mobile. We could work around that by modifying the user agent, but that is not supported in Safari.

https://lens.google.com/uploadbyurl?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F4%2F41%2FLethejalaurida.jpg

Uploading the image file to Google Images and Google Lens continues to work without issues on all platforms supported by the extension.

It looks like the bug still only affects some regions, I could only trigger the issue in Tor Browser with exit nodes from Sweden and Norway, but in other EU countries it worked as expected.

I think we should disable searching with an image URL entirely on Google Images, and upload the image instead so that it works for everyone regardless of your country. In a couple of weeks we will see if Google rolls out this change to all regions and we'll be in a better position to find a method for searching with an image URL that works on all platforms.

The next extension update will change how we search on Google and it will always upload the image, even with the "Select URL" search mode. I'll publish a new version in the next few days.

**Comment by dessant** [comment]
Has anyone from the US been affected by this bug when connecting from their home IP address?

**Comment by dessant** [comment]
Version 5.4.0 has been submitted to extension stores, you should receive an update in the next few days. I'll reopen this issue for better visibility.

**Comment by dessant** [comment]
Version 5.4.0 has been published everywhere.

**Comment by Chonkblonk** [comment]
This happens to me, and when I can get Google reverse image search to work, it seems to work a lot worse than before.

**Comment by BacchusPS** [comment]
Found this info on git from a on a similar extension with the same issue:

Due to a recent change in google image search client=firefox-b-d has to be added in the query. Any client name will do, as long as the client parameter has a value, but seems like firefox-b-d is the standard client name for queries originated from Firefox.

I don't know yet if this is a confirmed fix. Just thought it might be useful info.

**Comment by trlkly** [comment]
It may indeed just be a temporary thing, but I notice that every image I try to look up on Google Image Search currently gives this message, and has for nearly a day:

> Search by image is unavailable. Please try again in a few hours.

**Comment by dessant** [comment]
@trlkly, which extension version do you use? Please also share your browser, OS, and the country or continent you browse from.

**Comment by trlkly** [comment]
Open in Chrome version: 0.2.0 
Browsers tested: Microsoft Edge 109.0.1495.2, Chrome 107.0.5304.107
OS: Windows 10 Pro 19044.2130 (21H1)
And I'm in the United States (North America).

**Comment by trlkly** [comment]
Image Search version: 5.4.0
Browser: Chrome 107.0.5304.107
OS: Windows 10 Pro 19044.2130 (21H1)
Country: United States

**Comment by dessant** [comment]
@trlkly, thanks for the details! By Google View in your first comment you meant Google Lens?

**Comment by trlkly** [comment]
@dessant Yes, sorry.

**Comment by thaliel** [comment]
> It may indeed just be a temporary thing, but I notice that every image I try to look up on Google Image Search currently gives this message, and has for nearly a day:
> 
> > Search by image is unavailable. Please try again in a few hours.
> 
> Also, going through Google View and then clicking the Search by Image option still works. So clearly Search by Image isn't completely down.

same for me today, its was working fine before

**Comment by dessant** [comment]
The next update will restore searching directly with an image URL, and image uplading should also be fixed.

**Comment by dessant** [comment]
Version 5.4.2 has been published, make sure to install the latest version of the extension.

**Comment by Tiffys** [comment]
> Version 5.4.2 has been published, make sure to install the latest version of the extension.

Latest version available for Firefox is 3.0.12 last updated 3 years ago and it decidedly doesn't work with that one. Latest in the Chrome web store is 0.0.7.5 updated back in 2020 and it also doesn't work with that one.

**Comment by dessant** [comment]
@Tiffys, that does not sound right, you should follow the download links here to install the correct extension: https://github.com/dessant/search-by-image#readme
