### ISSUE TITLE
White screen when capturing on Facebook

### ISSUE THREAD

**Issue by assg4** [dessant/search-by-image#232]
**System**

* OS name: Windows
* OS version: 11
* Browser name: Firefoxx
* Browser version: 108.0.1 (64-bit)
* Extension version: 5.4.2

**Bug description**

This happens: https://i.imgur.com/MPItAvH.png

**Comment by dessant** [comment]
Were you using a dark theme? There's a relatively new browser behavior that makes an iframe background opaque when the iframe element and the embedded page have a different `color-scheme`. This bug was just fixed and will be part of the next release.

Ref https://github.com/dessant/search-by-image/commit/7db98b7ed0186c392f2569971360136368956cda.

**Comment by neoOpus** [comment]
> Were you using a dark theme? There's a relatively new browser behavior that makes an iframe background opaque when the iframe element and the embedded page have a different `color-scheme`. This bug was just fixed and will be part of the next release.
> 
> Ref [7db98b7](https://github.com/dessant/search-by-image/commit/7db98b7ed0186c392f2569971360136368956cda).

Finally, Thank you so much Armin
