### ISSUE TITLE
Google Lens returning "Something went wrong. Searching on Google Lens has failed."

### ISSUE THREAD

**Issue by spiderkitten** [dessant/search-by-image#273]
**System**

* OS name: MacOS 
* OS version:  10.14.6 Mojave
* Browser name: Brave
* Browser version: Version 1.57.64 Chromium: 116.0.5845.188 (Official Build) (x86_64)  
* Extension version:  1.2.1

**Bug description**
I right click on an image and select "Search by Image" in the context menu  
I choose either "All Search Engines" or "Google Lens"   
The search opens in a new tab. 
All the sites work, except Google Lens. 
Google Lens returns a "Something went wrong. Searching on Google Lens has failed." message. 

Note: Google Lens works fine when I don't use the extension, if I just search the image manually. 

**Logs**

```
TypeError: Cannot read properties of null (reading '1') 
Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at n.session (script.js:2:31453)
    at async Proxy.search (script.js:2:31054)
    at async Proxy.setup (script.js:2:28721)
```

**Comment by Whoami42** [comment]
Can confirm, I can't use Google Lens also for this reason

**Comment by haha0803** [comment]
出了些问题。在 Google Lens 上搜索失败。

**Comment by milenamilka755** [comment]
Win10, Chrome 117
Can confirm, I can't use Google Lens with this for this reason, but without the extension Google Lens standalone still works.

**Comment by dessant** [comment]
Hi everyone! Google has updated the Google Lens service, and there seems to be a new session token check on the server side, so the old method of uploading images will no longer work.

I have a local development version that works on desktop and mobile browsers, and it will be released this week. iOS and iPadOS users will need to update to Safari 16.4 or newer for Google Lens to continue working.

**Comment by GeorgeGR21** [comment]
I'm running Firefox 118.0.1 on Fedora Linux Silverblue 118 and I'm encountering the same issue. I was just about to report this but it was already reported. I'm glad there is a fix coming soon.

**Comment by dessant** [comment]
Version 5.8.0 includes the fix for Google Lens, and it is being uploaded to extension stores. You should receive the update in the next few days.

**Comment by AlbertoP64** [comment]
Can't update to 5.8.0 on Windows 8.1, so Google Lens problem keep going.
Is it expected (just because old win OS)?

**Comment by dessant** [comment]
> Can't update to 5.8.0 on Windows 8.1, so Google Lens problem keep going. Is it expected (just because old win OS)?

Chrome is no longer supported on Windows 8.1, if that's your browser. Firefox 115 ESR still supports Windows 8.1 until September 2024, but you should just update to Windows 10 instead.

**Comment by AlbertoP64** [comment]
Thanks @dessant, nope, my browser is Opera desktop (chrome clone) but also outdated version because of Os, should jump Os to 10 but have some hardware change to do and driver to provide.
Simply, until then, I add to the increasingly long collection of sw pieces no more working on my sys.
Seems that, OS dismissing is getting much more crudely mandatory than in the past.
If I wait enough, but not too long, just two years, it seems that also Win 10 will soon become obsolete (14 oct 2025), and so all my hardware :-( .
I should evaluate other ways.
I will not think to add also FFX ESR to my bunch, anyway.
For your extension, I will simply disable Google Lens in the UI and use copy / paste image on Google search -> Image.
