### ISSUE TITLE
Please, Add option to save image

### ISSUE THREAD

**Issue by jedikalimero** [dessant/search-by-image#29]
The ability of this Add-on to search images that usually don't activate the image related options in the context menu is remarkable. It is possible to search images hidden under a transparent gif, background images, images in Instagram or Twitter that are not easy to pick, etc.

So, I was wondering, why not apply all this potential to save that image?

I think it would be easy to add an option to the context sub-menu of search-by-image to just save the image instead of searching for it (and selecting what image to save when there are several candidates, as happens with searches)

I know this is not the main purpose of this add-on but I think it would be very easy and convenient to implement.

**Comment by dessant** [comment]
Thanks for the request, I've been playing with the idea to add the feature, since I also needed it a couple of times. Sadly I could not settle with myself about the way it would be integrated in the UI. The submenu or popup is not visible when only one engine is enabled, or when the extension is set to search all engines. It'd also feel out of place and arbitrary to list a 'Save Image' item next to search engine names, unless the engines are also grouped under 'Search Image', which then results in additional mouse movements for the user.

I've considered some of the features that one would expect once image saving is added, and the end result looked more like a new extension within this one.

It may be better to have an extension specialized for image saving where all these use cases can be handled, including bulk extraction from the full page or by selecting a page area.

I may come to create such an extension in the future, but I don't have any immediate plans. For now we'll have to fish out the URL with the element inspector. :yum:

**Comment by jedikalimero** [comment]
I understand your point of view. It would be more sensible to create a new extension that shares the same techniques for finding the image.
In the meanwhile, I managed to find a way to achieve what I wanted: If I search with TinEye, Next to the miniature of the image in the top of the results page, TinEye shows the URL of the image in a link, so it is just a matter of clicking it and saving the image as usual. It doesn't matter if TinEye finds any coincidence or not.

**Comment by dessant** [comment]
Hi @jedikalimero, the next version of the extension will open the image you select in a new tab, see this issue for details: https://github.com/dessant/search-by-image/issues/117
