### ISSUE TITLE
Ability to search for Imgur's gifv files.

### ISSUE THREAD

**Issue by Browsar** [dessant/search-by-image#4]
Would it be possible to implement the ability to search for Imgur's gifv files? I've seen several older Firefox add-ons with an ability to do this, but would like to see it in your extension.

**Comment by dessant** [comment]
That's a nice idea!
It seems it can be done by changing the extension to `gif`. As a workaround until the next release, you can replace `gifv` with `gif` and load the image, then search from there.

**Comment by dessant** [comment]
I've looked into this and I'm not sure it is even needed. Imgur serves a html page for the gifv extension, with a video element which has a poster. The poster is found by the add-on and searching for it seems to work with the latest version.

Please share a link or use case where the search fails unless the file extension is changed, and I'll reopen the issue.

Otherwise it can be implemented like this:
```js
imgUrl = imgUrl.replace(/(.*\.)gifv($|\?.*|#.*)/, '$1gif$2');
```

**Comment by dessant** [comment]
Ok, I was testing with a direct link (http://i.imgur.com/wmP5qwl.gifv), not a page (http://imgur.com/wmP5qwl). The page does not declare a video poster, so the image is not found.

**Comment by dessant** [comment]
It would be easy to extract the gifv poster on Imgur, but I do not intend to handle specific sites in the parser. As explained in my previous comment, on direct gifv links the image is extracted from the video poster and searching works.

Please contact Imgur support to declare video posters on gifv pages too.
https://help.imgur.com/hc/en-us/requests/new

**Comment by dessant** [comment]
One can search for the current video frame with the extension, so Imgur gifv should also work now.
