### ISSUE TITLE
Add/Edit search engine.

### ISSUE THREAD

**Issue by AussieGit** [dessant/search-by-image#50]
Is there a way to add or edit an existing search engine?

**Comment by dessant** [comment]
The extension does not support adding a custom engine, and it's not practical to add such a feature because most engines have their own quirks that need to be handled by the extension.

Which search engine did you want to add?

**Comment by AussieGit** [comment]
. Thanks for taking the time to get back to me. To me, that is a sign that a developer cares about their work so thank you. I was looking for aliexpress.com and the English version of Alibaba.com

**Comment by dessant** [comment]
I've been planning to add both, but the websites lack the feature, I've only seen it on the mobile apps. So the only way for now is to use the APIs called by mobile apps, and present the results on a local page, like we do with Pinterest.

**Comment by DumbJoe** [comment]
> The extension does not support adding a custom engine, and it's not practical to add such a feature because most engines have their own quirks that need to be handled by the extension.

Then explain this addon: https://addons.mozilla.org/en-US/firefox/addon/image-search-options/?src=collection#&gid=1&pid=2 which touts custom search engines that you can add yourself?

> Users are free to **add their own sites**, customize existing ones, and search multiple sites at a time.

Also while we're here, may as well steal something else from them, they have ImgOps search engine which you do not currently have....

**Comment by dessant** [comment]
@DumbJoe, that extension supports only a subset of features offered by Search by Image and it has its limitations. For example, whenever an image needs to be uploaded to a search engine, the image is uploaded to an intermediary host and searching is done with a URL rather than uploading the image directly to the search engine. Even with that workaround, only search engines that do not use any temporary tokens or client side magic are supported.

I have thought about implementing custom search engine support, but the feature would be brittle and only work with certain engines, unless it would become a mini-framework for website automation and allow custom scripts, none of which are desirable.

I find that time much better spent by adding proper support for search engines that people need. Feel free to suggest reverse image search services that you would like to see implemented.

Regarding ImgOps, all of the reverse image search services implemented by it are supported by this extension, and the rest of its tools do not belong in this extension.

**Comment by DumbJoe** [comment]
Oh I see....

> Regarding ImgOps, all of the reverse image search services implemented by it are supported by this extension, and the rest of its tools do not belong in this extension.

Ah well I saw the description and no where does it list that as a reverse search engine.....that's why....
