### ISSUE TITLE
Firefox - Yandex search query has stopped working

### ISSUE THREAD

**Issue by Wileecoyote1969** [dessant/search-by-image#55]
Windows 10
Firefox
67.0.4 (64-bit)
Extension version: 1.21.0

The Yandex portion of the Image Search Add-on has stopped working, I guess Yandex changed their code or something, as Yandex is still working on it's own, just not through your Add-on. This is sad news because out of all the options included in your Add-on Yandex, Google, Bing and Tineye are the only ones that provide consistent results for me. I know you are busy, hope when you have the time you can look at it

**Comment by dessant** [comment]
It works on my part, please share more details, an image URL could also help. Are you seeing yandex.com in the URL bar or a different TLD?

**Comment by Wileecoyote1969** [comment]
Just a quick example
This image (pulled randomly off the internet)

https://article.images.consumerreports.org/prod/content/dam/CRO%20Images%202019/Cars/January/CR-Cars-InlineHero-2019-Acura-ILX-A-Spec-f-1-19

returns this result in the address bar, but leaves the page blank

https://yandex.com/images/search?img_url=https%3A%2F%2Farticle.images.consumerreports.org%2Fprod%2Fcontent%2Fdam%2FCRO%2520Images%25202019%2FCars%2FJanuary%2FCR-Cars-InlineHero-2019-Acura-ILX-A-Spec-f-1-19&rpt=imageview

If I search the same image on Yandex's page there is no problem, it is the exact same URL, the page is not blank.

However I just installed your add-on on a computer which is still running 57.0 FireFox and everything works fine. I'm going to update FireFox on that computer and see what happens

**Comment by dessant** [comment]
The site uses a new URL parameter, `url` instead of `img_url`. However, your link and the extension works for me on the latest Firefox.

Please clear your browsing data or use a fresh profile before loading the first then the second URL.

https://yandex.com/images/search?url=https%3A%2F%2Farticle.images.consumerreports.org%2Fprod%2Fcontent%2Fdam%2FCRO%2520Images%25202019%2FCars%2FJanuary%2FCR-Cars-InlineHero-2019-Acura-ILX-A-Spec-f-1-19&rpt=imageview

https://yandex.com/images/search?img_url=https%3A%2F%2Farticle.images.consumerreports.org%2Fprod%2Fcontent%2Fdam%2FCRO%2520Images%25202019%2FCars%2FJanuary%2FCR-Cars-InlineHero-2019-Acura-ILX-A-Spec-f-1-19&rpt=imageview

Test them without installing the extension, which one does load?

**Comment by Wileecoyote1969** [comment]
Here's the deal:

my other older computer, running Win7, the one I just installed your add-on to and had issues when I upgraded FireFox, I got that one working. It was just a hiccup with the FireFox upgrade.

I feel fairly certain that the issue is on my end and that it is just something I will have to sort out. 

My apologies for dragging you through this, I really love you add-on, literally use it every day. It is easily the best and simplest multiple image search function out there

Thanks for all your responses!

**Comment by Wileecoyote1969** [comment]
Stop everything! Hope I'm not too late to add this, cause this is new and just happened

https://i.imgur.com/SRlBpyN.jpg

While doing an image search the Yandex tab hit me with this. First time it ever did this. Apparently Yandex may have been ignoring the requests as an anti-bot measure. At least this helps confirm my suspicion that Yandex might have been causing the issue

**Comment by dessant** [comment]
That's ok, I'm glad you like the extension!

Captchas can appear after repeated searches even if you don't use the extension.
