### ISSUE TITLE
Search by Image removed from Chrome Web Store

### ISSUE THREAD

**Issue by rogersachan** [dessant/search-by-image#57]
Will it ever be republished?

**Comment by dessant** [comment]
Action Required: Search by Image Requires Changes to Comply with Chrome Web Store Policy

chromewebstore-dev-support@google.com <chromewebstore-dev-support@google.com>	Thu, Jul 11, 2019 at 5:58 AM
To: *****@gmail.com
Cc: chromewebstore-dev-support@google.com

Dear Developer,

We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users. We recently found that your item, "Search by Image," with ID: cnojnbdhbhnkbcieeekonklommdnndci did not comply with our policies. Your item did not comply with the following section of our policy: Do not use irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata. Please ensure that your item has a description that clearly and directly relates the functionality of your extension.Your item is still published, but is at risk of being removed from the Web Store.

Please make the above changes within 7 days in order to avoid removal: Once you have made these changes you may submit and publish a new draft in the developer dashboard. Your draft will be reviewed for policy compliance which typically takes a few business days. If the outcome of the review is successful, your store listing will remain published. If we find additional issues with your item, we will send you another email with details. If you have any questions about this email, please respond and the Chrome Web Store developer support team will follow up with you.

Important Note:

Your item will still be subject to review and may be removed from the store within the warning period. Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform. This may also result in the suspension of related Google services associated with your Google account.

Thank you for your cooperation,

Google Chrome Web Store team


Developer Terms of Service: https://developers.google.com/chrome/web-store/terms

Program Policies: https://developers.google.com/chrome/web-store/program_policies

Branding Guidelines: https://developers.google.com/chrome/web-store/branding

---

Armin S. <*****@gmail.com>	Thu, Jul 11, 2019 at 9:01 AM
To: chromewebstore-dev-support@google.com

Hi!

I don't see anything irrelevant, misleading, or excessive in the description of the extension that would warrant a removal. Which part of the description do you believe should be changed?

---

chromewebstore-dev-support@google.com <chromewebstore-dev-support@google.com>	Thu, Jul 11, 2019 at 9:00 PM
To: "Armin S." <*****@gmail.com>

Dear Developer,

We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users.

Your item did not comply with the following section of our policy:
Do not use irrelevant, excessive keywords in app descriptions. Ex: Search engines

To have your item reinstated, please ensure excessive words or tags do not appear in the description of your item.

Thank you for your cooperation,
Google Chrome Web Store team

Please take a minute and click on the link to answer a quick survey below about your experience with us so we can improve our service- https://goo.gl/forms/*****

---

Armin S. <*****@gmail.com>	Fri, Jul 12, 2019 at 4:26 PM
To: chromewebstore-dev-support@google.com

Hi!

The list of supported search engines is an essential part of the description, and it was added based on user feedback. New users would often remark that a specific search engine was not supported, or submitted feature requests, when in fact the search engine was already supported by the extension. Having an explicit list of search engines available in the description helps users discover the extension and decide whether or not it meets their needs.

I believe listing the search engines supported by the extension benefits users, and it is no way irrelevant or excessive.

I'm hoping that you will reassess the interpretation of the cited policy in the context I have shared with you, and reinstate the extension.

Thanks a lot,
Armin Sebastian

---

chromewebstore-dev-support@google.com <chromewebstore-dev-support@google.com>	Sat, Jul 13, 2019 at 2:54 PM
To: "Armin S." <*****@gmail.com>

Dear Developer,

We have reviewed your item and it does not comply with our program policies. Please re-review this section of our policy:

https://developer.chrome.com/webstore/program_policies#extensions

If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal.

---

Armin S. <*****@gmail.com>	Sat, Jul 13, 2019 at 3:27 PM
To: chromewebstore-dev-support@google.com

Search by Image is an open source project that is used in part by journalists to verify the integrity of stories and information sources.

The extension has a single purpose, and that is to provide a reverse image search tool. The listing does not contain bundles of unrelated functionality, every single feature is closely tied to searching using images.

If you have noticed unrelated functionality within the extension, please mention which feature does not comply with the linked section of the policy.

---

chromewebstore-dev-support@google.com <chromewebstore-dev-support@google.com>	Sun, Jul 14, 2019 at 4:59 AM
To: "Armin S." <*****@gmail.com>

Dear Developer,

We have reviewed your item and it does not comply with our program policies. Unfortunately, we cannot provide any additional information regarding this issue. Please re-review the policies as previously specified.

Thank you for your cooperation,
Google Chrome Web Store team

---

Armin S. <*****@gmail.com>	Sun, Jul 14, 2019 at 8:35 AM
To: chromewebstore-dev-support@google.com

We would be happy to resolve the issue, but it's not clear exactly which feature is not compliant. The linked sections of the policy have been re-reviewed, and the extension does not contain bundles of unrelated functionality.

Search by Image is a featured extension that has gained recommended status on Firefox. It would be unfortunate to lose this extension on Chrome over an issue we don't even understand.

https://addons.mozilla.org/en-US/firefox/guides/enhance-your-media-experience/
https://addons.mozilla.org/en-US/firefox/addon/search_by_image/

Please share more details and specify exactly which feature is not compliant in order to resolve the issue.

Thanks a lot,
Armin Sebastian

---

chromewebstore-dev-support@google.com <chromewebstore-dev-support@google.com>	Mon, Jul 15, 2019 at 8:00 AM
To: "Armin S." <*****@gmail.com>

Dear Developer,

We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users.

Your item did not comply with the following section of our policy:
Do not excessive keywords in app description such as name of supported search engines.

To have your item reinstated, please ensure excessive words or tags do not appear in the description of your item.

Thank you for your cooperation,
Google Chrome Web Store team

Please take a minute and click on the link to answer a quick survey below about your experience with us so we can improve our service- https://goo.gl/forms/*****

---

Armin S. <*****@gmail.com>	Mon, Jul 15, 2019 at 9:23 AM
To: chromewebstore-dev-support@google.com

I have published an updated app description without the list of supported search engines.

Thanks a lot,
Armin Sebastian

**Comment by dessant** [comment]
Chrome Web Store: Removal notification for Search by Image

Chrome Web Store <chromewebstore-noreply@google.com>	Mon, Jul 15, 2019 at 7:24 AM
To: *****@gmail.com

Dear Developer, Your Google Chrome item, "Search by Image," with ID: cnojnbdhbhnkbcieeekonklommdnndci did not comply with our policies and was removed from the Google Chrome Web Store. Your item did not comply with the following section of our policy: Do not use irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata. Please ensure that your item has a description that clearly and directly relates the functionality of your extension.If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal. *Please keep in mind that your re-submitted item will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published if the item passes review. *Important Note Repeated or egregious violations in the store may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to Chrome Web Store policies and terms of service. Thank you for your cooperation, Google Chrome Web Store team --------------------------- Developer Terms of Service: https://developers.google.com/chrome/web-store/terms Program Policies: https://developers.google.com/chrome/web-store/program_policies Branding Guidelines: https://developers.google.com/chrome/web-store/branding

---

Chrome Web Store <chromewebstore-noreply@google.com>	Mon, Jul 15, 2019 at 9:18 AM
To: *****@gmail.com

Dear Developer, Your Google Chrome item, "Search by Image," with ID: cnojnbdhbhnkbcieeekonklommdnndci did not comply with our policies and was removed from the Google Chrome Web Store. Your item did not comply with the following section of our policy:

Do not post repetitive content. 
Do not attempt to change the placement of any Product in the store, or manipulate any Product ratings or reviews, by unauthorized means, such as fraudulent installs, paid or fake reviews or ratings, or offering incentives to rate Products. 
Do not post an app if the primary functionality is to link to a website not owned by the developer posting the app. 
Do not post an app where the primary functionality is to install or launch another app, theme, or extension. For example, you cannot post an app if its primary function is to launch a desktop app that the user has already installed. Another example of a disallowed practice would be to post a packaged app that just launches a website. 
Your app must comply with Google's Webmaster Quality Guidelines

**Comment by rogersachan** [comment]
https://support.google.com/chrome_webstore/contact/developer_support/?hl=en You might be able to get a human being to respond to you here. Other than that if they refuse to let the description through you can always post it on the [Edge Insider extension store](https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions) (the new edge is based on chrome).

**Comment by dessant** [comment]
In essence they took issue with the extension description listing the supported search engines, and I have tried to explain why it's important to list those engines in the description.

Instead of acknowledging my message, the reviewer went on to state that now there was a bigger issue, the extension is a bundle of unrelated features, which it isn't.

I have tried to further explain hoping that it will be realized that a mistake is being made, and as a reaction the reviewer took down the extension 3 days before the initial 7 day deadline has passed, and listed several additional policy violations that do not make any sense.

The chances of the extension being relisted are slim, and judging by similar extension takedowns it depends on how much attention this issue gets on social media.

They are clearly making a mistake, but there is no point in continuing if they are not willing to listen to reason.

This is how users suffer and useful open source projects are lost because of Chrome's monopoly.

**Comment by dessant** [comment]
I have posted the issue to Twitter an HN, maybe it gets some traction and the extension is relisted.

https://twitter.com/dessantx/status/1150807970697097216
https://news.ycombinator.com/item?id=20442594

**Comment by dessant** [comment]
chromewebstore-dev-support@google.com <chromewebstore-dev-support@google.com> | Tue, Jul 16, 2019 at 8:47 AM
To: "Armin S." <*****@gmail.com>

Dear Developer,

To have your item reinstated, please re-publish it in your developer dashboard.

**Comment by dessant** [comment]
I have published the extension again. Previous attempts were rejected automatically with the [second message](https://github.com/dessant/search-by-image/issues/57#issuecomment-511466276), this time it has entered in "Pending Review".

**Comment by dessant** [comment]
The extension was reinstated without further explanation.

https://chrome.google.com/webstore/detail/search-by-image/cnojnbdhbhnkbcieeekonklommdnndci
