### ISSUE TITLE
Baidu url's target has been abandoned

### ISSUE THREAD

**Issue by dalu98** [dessant/search-by-image#67]
**System**

* OS name: macOS
* OS version: 10.15.3
* Browser name: Firefox
* Browser version: 73.0
* Extension version: 2.1.0

**Bug description**

 'https://image.baidu.com/n/pc_search' has been abondoned, open this in browser will lead to a wrong website which will not to search images by baidu.

 I think it should be repalced by 'https://image.baidu.com/search' now.

But I don't know how to pack this src to test in my browser, I think the problem should be in this line.

https://github.com/dessant/search-by-image/blob/d4d61707e2c4c8a3ffed70777d5d418e7e1e8bdf/src/utils/data.js#L56

**Comment by dessant** [comment]
Hi, thanks for the bug report, I'll update the Baidu URL.

I've been looking for a way to test the extension from Mainland China, because Jingdong has stopped working.

If you've in China, could you check with your local internet connection if the reverse image search feature is available for this site?

https://www.jd.com

Are you redirected to https://global.jd.com, and if not, do you see a camera icon in the search bar?

**Comment by dalu98** [comment]
> Hi, thanks for the bug report, I'll update the Baidu URL.
> 
> I've been looking for a way to test the extension from Mainland China, because Jingdong has stopped working.
> 
> If you've in China, could you check with your local internet connection if the reverse image search feature is available for this site?
> 
> https://www.jd.com
> 
> Are you redirected to https://global.jd.com, and if not, do you see a camera icon in the search bar?

Yes, I can access both of them. But I don't think you can search items by image on Jingdong's main website. 

![jd](https://user-images.githubusercontent.com/25452934/74599218-67457b00-50b9-11ea-8764-a4a624a9cb54.jpg)

![jd-global](https://user-images.githubusercontent.com/25452934/74599295-69f4a000-50ba-11ea-81b0-ce8d6af1eb1f.jpg)


I think you should use https://search.jd.com/ instead. On this website, it has a search bar with a camera icon in it.

![jd-search](https://user-images.githubusercontent.com/25452934/74599350-4aaa4280-50bb-11ea-9b39-3346a3557f7b.jpg)

However, after I click the camera icon and upload images on my computer, the website doesn't have any reaction... Maybe Jingdong just closes this, and only can be used by the Jingdong APP on mobile phone. 

But on this website it says images can be used to search on Jingdong website, you can see it in this website: https://blog.csdn.net/Alex20182019/article/details/104209222

And after I paste 'https://search.jd.com/image?path=jfs/t1/932/25/457/44818/5b8ff7cbE8027c4ed/f334304e50617cab.jpg&op=search' in url and hit `<return>`, it worked. 

![jd-image](https://user-images.githubusercontent.com/25452934/74599426-9c070180-50bc-11ea-8cd3-f23f366229ec.jpg)

So I think you just need to replace the value(the path of image) between `path=` and `&op=search`? I don't actually know how to make it work, but I hope this can be helpful to you :)

Thanks!

**Comment by dessant** [comment]
Thanks a bunch for your research, this has been very informative! :yellow_heart: 

Please let me know if there's any other popular Chinese website that offers reverse image search and isn't already supported.

**Comment by dalu98** [comment]
OK, I have tested `Qihoo`, `taobao`, `Alibaba China` and `sogou`. 

All of them worked well except `Alibaba China`.  When I search image by `Alibaba China`, I only got the homepage: https://www.1688.com/ and didn't search it by image.

But it works when I click the camera icon in the search bar, the return url's value is: https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/kZpzBtRf2C1581830609000.jpg

**Comment by dalu98** [comment]
I test `Alibaba China` several times, and the only difference between these results in url is that the value after `https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageType=oss&imageAddress=cbuimgsearch/` changed.

**Comment by dessant** [comment]
Thanks again for testing, it looks like Alibaba has changed the DOM for the camera icon, which the extension needs to select. I'll release an update next week for all the discussed search engines.

Do you know any other Chinese site that has reverse image search accessible from their website? I've looked around a lot at the time, but these were the ones I could find.

I'm aware of a couple of other commerce sites that have Android apps with reverse image search, though implementing those will be a bit more difficult, since the image search feature has no user interface accessible from the web.

**Comment by dalu98** [comment]
You're welcome 😂, hope you can make this extension better~

As for other chinese site, I think the vast majority of Mainland Chinese use `Baidu`/`Sogou` to search(some prefer `Google`), and `Baidu`/`Sogou` they split up 90% of the Chinese search engine market. The remaining market share is mainly divided by some search engines that are rarely used such as `shenma`(this can be only used on mobile phone) and `Qihoo`.

For shopping, `Taobao` and `Jingdong` cover most shopping scenarios.

But if I have found any other common search engines, I will commit it to you :)

**Comment by dessant** [comment]
Baidu has been fixed in https://github.com/dessant/search-by-image/commit/a697c4ac9858a22f28ebc7f498636c189f0e297a, and Alibaba in https://github.com/dessant/search-by-image/commit/e2002377cf5743f1cbba0391146389639d996198.

I can't fully test Baidu from the EU, it loads the search results page, but it is broken, though I guess it loads correctly from China.

![](https://i.imgur.com/1dBxBvs.png)

I'll leave Jingdong for now, previously there was a camera icon in the search bar of https://www.jd.com, now it appears for a moment as the page loads and it is quickly removed, and as you've seen it is also broken on https://search.jd.com. I think they have temporarily turned off the feature. The post you found describes Jingdong's search API, which is not public and requires an API key. We'll wait a bit to see if they bring the feature back.

**Comment by dalu98** [comment]
It's working well now, thanks for your work!
