### ISSUE TITLE
Unclear setting options

### ISSUE THREAD

**Issue by alexolog** [dessant/search-by-image#69]
Please document the following options:
- Use local Google site
- Look above and below <img> elements

I could not find any explanation on what they do and when they should be enabled.

Thank you.

**Comment by dessant** [comment]
If "Use local Google site" is turned off, Google search results are always loaded from google.com in English, and not the localized Google site.

The "Look above and below `<img>` elements" option controls what to do when there is an `<img>` element at the clicked area.

Similar extensions can only detect `<img>` elements during an image search, but this extension performs collision detection to see if there are images declared in a different way at the clicked area.

If the clicked element is an `<img>`, the extension does not further parse the page, because then it would pick up background images and similar stuff, which would result in multiple images being found, and a popup to select which image you want to search for from the ones that were found.

So the second option is esentially for convenience, to not regularily see selection popups as you search, because images are predominantly declared as `<img>` elements on the web.

There may be times when you want to enable the option, such as when an image with a transparent background overlaps something else. For example, there may be a play button above a video that gets picked up by the extension, but you want to search for the current video frame instead.

**Comment by alexolog** [comment]
Thanks!
