### ISSUE TITLE
Taobao does not work

### ISSUE THREAD

**Issue by mon1242323** [dessant/search-by-image#82]
It redirects to the homepage instead of searching the image 
<img width="1228" alt="Screen Shot 2563-06-20 at 13 32 24" src="https://user-images.githubusercontent.com/67182446/85195170-9b94a680-b2fa-11ea-9ae7-7562c0db68b8.png">

**Comment by dessant** [comment]
Reverse image search has been available only on https://www.taobao.com. Until now we could change the locale to Mainland China (中国大陆) on the top left, but now it seems https://www.taobao.com redirects to https://world.taobao.com regardless of the locale. They could have started redirecting based on the IP address, and searching with Taobao now only works from Mainland China, or they have made the image search feature exclusive to their mobile app.

If you're using the extension from China, please test and share under what circumstances does the image search button appear in the search bar on Taobao.

**Comment by dessant** [comment]
The issue is documented here: https://github.com/dessant/search-by-image/issues/74

There is nothing the extension can practically do when reverse image searches are geoblocked. Please share more details if you're having issues from Mainland China and the image search button is otherwise visible in the search bar.
