### ISSUE TITLE
Nor working for me at all from today

### ISSUE THREAD

**Issue by rakitanc** [dessant/search-by-image#92]
**System**

* OS name: Linux MInt
* OS version: 19.3 Cinnamon
* Browser name: Chrome
* Browser version: 85
* Extension version: 3.0.0

**Bug description**

**Comment by dessant** [comment]
Which search engine?

**Comment by rakitanc** [comment]
> Which search engine?

No Search engine is working

**Comment by dessant** [comment]
It helps to be more specific so that I don't have to spend my time figuring out what doesn't work on your device. I guess you're referring to videos, as static images work on Imgur.

https://imgur.com/gallery/WMPgGIO

Chrome prevents extensions from exporting the canvas when it contains data from different origins, while the same will work in Firefox from the context of content scripts.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData

You can work around the issue in Chrome by pausing the video and switching to the Capture search mode to select a page area for searching, or by using Firefox.

**Comment by dessant** [comment]
The issue is tracked here: https://github.com/dessant/search-by-image/issues/93
